apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-secret
  namespace: kafka
type: Opaque
data:
  AUTH_TYPE: TE9HSU5fRk9STQ== #LOGIN_FORM
  SPRING_SECURITY_USER_NAME: YWRtaW4= #admin
  SPRING_SECURITY_USER_PASSWORD: YWRtaW4= #admin
  BASE_URL: L2s4cw==
