apiVersion: skaffold/v4beta10
kind: Config
build:
  artifacts:
    - image: iambks/auth
      context: services/auth
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
      docker:
        dockerfile: Dockerfile
    - image: iambks/client
      context: services/client
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
      docker:
        dockerfile: Dockerfile
    - image: iambks/conversation
      context: services/conversation
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/deployments/*
    - infra/k8s/secrets/*
    - infra/k8s/config/*
    - infra/k8s/loadbalancers/ingress.yaml
deploy:
  kubectl: {}

