apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: iambks/auth
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: auth-config
                key: PORT
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: auth-config
                key: NODE_ENV
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: DATABASE_URL
          - name: KAFKA_HOST
            valueFrom:
              secretKeyRef:
                name: kafka-secret
                key: KAFKA_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: kafka
spec:
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 4000
    targetPort: 4000

